name: Greeting on var day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Thursday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Monty it's Thursday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Monty
